services:
  app:
    build:
      context: .
      target: dev
    container_name: expenses-app-dev
    volumes:
      - ./:/app
      - m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/expenses_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-2.0-flash}
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: expenses-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expenses_tracker
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mysql_data_dev:/var/lib/mysql

volumes:
  m2:
  mysql_data_dev:
